### ISSUE TITLE
AnimationModule on Angular options is no longer needed

### ISSUE THREAD

**Issue by OriolInvernonLlaneza** [CanopyTax/single-spa.js.org#494]
The [Basic Usage > Options](https://single-spa.js.org/docs/ecosystem-angular/#options) section of the Angular documentation is not updated to reflect that AnimationModule is no longer needed since [Angular 12](https://github.com/single-spa/single-spa-angular/pull/362#discussion_r640985305).

**Comment by internettrans** [comment]
Fixed in #496
