### ISSUE TITLE
Slack link no longer working

### ISSUE THREAD

**Issue by Svreber** [CanopyTax/single-spa.js.org#501]
Hi, and thanks in advance.

**Describe the bug or question**
I am unable to connect to Slack via the link provided in the single-spa.js.org website (and the single-spa Github readme).

**To Reproduce**
Try to subscribe to the single-spa community in Slack using the link from the website or Github.

**Expected behavior**
Expect to be able to connect to the Slack community when clicking 'Join Slack Community'.

**Screenshots and/or console output**
When using the provided link:
![Capture d’écran du 2021-11-18 16-46-39](https://user-images.githubusercontent.com/2393978/142448552-14e7b4cb-c355-4993-8f38-00dc1a5747cd.png)

**Comment by filoxo** [comment]
Thanks for raising this issue for us! Here is an updated link: https://join.slack.com/t/single-spa/shared_invite/zt-yxfqpl2u-PNx3uZtS3pgAXbOBWsdwOA
I'll submit a PR with a fix for the documentation site shortly.

**Comment by filoxo** [comment]
I also updated the link on the single-spa repo README (https://github.com/single-spa/single-spa/commit/bcea338aff9231bacf9926ffc7b70dfe83e9f6eb).
