### ISSUE TITLE
SIngle-spa slack workspace invitation link is invalid

### ISSUE THREAD

**Issue by mikana0918** [CanopyTax/single-spa.js.org#533]
**Describe the bug or question**
A clear and concise description of what the bug or question is.

**To Reproduce**
For bugs, create a small git repo or codepen that reproduces the problem, and provide steps on how to see the issue. This is also helpful for questions.

**Expected behavior**
A clear and concise description of what you expect or hope to happen.

**Screenshots and/or console output**
If applicable, add screenshots or console output to help explain your problem.

**Additional context**
Add any other context about the problem or question here.

**Comment by filoxo** [comment]
Thanks for the heads up @mikana0918! I've submitted a PR to fix this. As a validation step, could you look at that PR and use the URL there to sign up for the Slack workspace? Just as a sanity check that it actually works. Thanks!

**Comment by mikana0918** [comment]
@filoxo Thank you for your reply! sure let me check out yours
