### ISSUE TITLE
Wrong param type in checkActivityFunctions function

### ISSUE THREAD

**Issue by cjosue15** [CanopyTax/single-spa.js.org#565]
We need to update the api documentation, in order to change from `URL` to `Location` the parameter in `checkActivityFunctions`.
This issue was reported here [#1000](https://github.com/single-spa/single-spa/issues/1000)

**Comment by cjosue15** [comment]
i just made a PR to fix it [#566](https://github.com/single-spa/single-spa.js.org/pull/566)

**Comment by filoxo** [comment]
Resolved in #566
