### ISSUE TITLE
"ADD YOUR COMPANY" button stopped working

### ISSUE THREAD

**Issue by exiadbq** [CanopyTax/single-spa.js.org#584]
<img width="806" alt="image" src="https://user-images.githubusercontent.com/4665929/234507013-e6aee805-241e-4db4-9902-d9db2169b145.png">

Just catching up on @joeldenning old ng podcast last year, and I worked for 3 companies, and 2 of them successfully implemented single-spa, one with sofe when it is still a thing.

So trying to give some mental support here, it's been many years. 👍

**Comment by MilanKovacic** [comment]
Link is fixed. Feel free to add the companies :)
